name: 'Save Feed Cache'
description: 'Composite action to save feed cache'

inputs:
  save:
    description: 'Whether to save the feed cache'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Save feed cache
      if: ${{ inputs.save == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          .cache
          public/images/feed-thumbnails
          public/images/feed-icons
        key: ${{ runner.os }}-feed-${{ github.run_id }}
