name: Generate feeds and site

on:
  push:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎日 8/12/16/20時に実行
    - cron: 0 23,3,7,11 * * *
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - uses: ./.github/actions/restore-feed-cache
      - run: npm run feed-generate
      - run: npm run site-prepare
      - run: npm run site-build
      - uses: ./.github/actions/save-feed-cache
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
